# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/jeweler-utils
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: vkaloidis
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: vkaloidis
          POSTGRES_DB: ruby24
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Install Gems
      - run: bundle

      # Run Tests
      - run: bin/test

      # Store Test Results
      - store_test_results:
          path: test/reports
